export const texts = [
  "Code is an art; craft it well.",
  "Sunsets and rises inspire.",
  "Algorithms shape the digital.",
  "Coffee fuels programmer's mind.",
  "Learning refreshes the mind.",
  "Music sparks creative minds.",
  "Sky full of stars at night.",
  "Innovation defines leaders.",
  "Nature speaks in its way.",
  "Every problem has a fix.",
  "Books open doors to worlds.",
  "Tech is a tool, not master.",
  "Moonlight creates serene.",
  "AI transforms industries.",
  "Kindness means everything.",
  "Journey starts with a step.",
  "Dance like no one's watching.",
  "Universe is full of wonders.",
  "Curiosity fuels discovery.",
  "Silence is the best answer.",
  "Challenges make life interesting.",
  "Pen is mightier than sword.",
  "Simplicity is ultimate.",
  "Rain cleanses the soul.",
  "Code is elegant poetry.",
  "Success is small efforts.",
  "Happiness is a choice.",
  "Earth has music, listen.",
  "Imagination over knowledge.",
  "Colors speak louder.",
  "Programming is superpower.",
  "Balance is key to life.",
  "Future belongs to dreamers.",
  "Embrace glorious imperfection.",
  "Mindset shapes everything.",
  "Early bird catches worm.",
  "Seek joy in the little things.",
  "Embrace the beauty of now.",
  "Courage overcomes any fear.",
  "Explore, dream, discover.",
  "Cherish each fleeting moment.",
  "Grow through life's challenges.",
  "Smile, let happiness in.",
  "Create your own sunshine.",
  "Find peace within chaos.",
  "Sparkle with inner light.",
  "Love deeply, forgive freely.",
  "Strive for continuous improvement.",
  "Imagine, believe, achieve.",
  "Dance in the rain.",
  "Kindness changes everything.",
  "Dreams fuel the soul.",
  "Infinite possibilities await.",
  "Be a voice, not an echo.",
  "Shine like the stars.",
  "See miracles in the ordinary.",
  "Leap into the unknown.",
  "Embrace the journey within.",
  "Discover your inner strength.",
  "Sow seeds of positivity.",
  "Chase your wildest dreams.",
  "Celebrate your uniqueness.",
  "Pause, breathe, proceed.",
  "Adopt an attitude of gratitude.",
  "Radiate positive vibes.",
  "Nourish your mind daily.",
  "Embrace the magic within.",
  "Strive for progress, not perfection.",
  "Find solace in nature's beauty.",
  "Live authentically, be you.",
  "Craft your own destiny.",
  "Believe in your potential.",
  "Awaken the adventurer within.",
  "Love unconditionally, without expectations.",
  "Discover the power of simplicity.",
  "Create ripples of kindness.",
  "Pause and appreciate life.",
  "Radiate positive energy.",
  "Savor life's sweet moments.",
  "Live with purpose and passion.",
  "Conquer from within.",
  "Cherish the gift of time.",
  "Be the change you seek.",
  "Dwell in possibility.",
  "Write your own story.",
  "Embrace your true self.",
  "Celebrate small victories daily.",
  "Strive for inner peace.",
  "Explore the unknown fearlessly.",
  "Let your heart guide.",
  "Dance through life's storms.",
  "Seeds of kindness bloom joy.",
  "Believe in your resilience.",
  "Be a beacon of hope.",
  "Live with no regrets.",
  "Radiate love and light.",
  "Find strength in adversity.",
  "Live intentionally, not habitually.",
  "Embrace the journey's lessons.",
  "Chase experiences, not things.",
  "Embrace the beauty of change.",
  "Find joy in simple pleasures.",
  "Cultivate a grateful heart.",
  "Be the hero of your story.",
  "Discover your inner fire.",
  "Dwell in gratitude daily.",
  "Create your sunshine moments.",
  "Seek beauty in diversity.",
  "Radiate kindness effortlessly.",
  "Dream without limitations.",
  "Nurture your inner child.",
  "Celebrate your growth journey.",
  "Be present, be mindful.",
  "Embrace the unknown boldly.",
  "Find peace in stillness.",
  "Chase sunsets, not followers.",
  "Create a life you love.",
  "Nourish your soul daily.",
  "Let love guide your actions.",
  "Shine in your authenticity.",
  "Celebrate the power of now.",
  "Cherish connections deeply.",
  "Live with genuine enthusiasm.",
  "Radiate confidence and kindness.",
  "Dream, believe, achieve.",
  "Sow seeds of positive change.",
  "Dance through challenges gracefully.",
  "Find strength in vulnerability.",
  "Discover the joy of giving.",
  "Chase passions, not perfection.",
  "Embrace the beauty of beginnings.",
  "Cultivate an attitude of gratitude.",
  "Nourish your mind with wisdom.",
  "Live a life of purpose.",
  "Celebrate the uniqueness within you.",
  "Creativity is fun intelligence.",
  "Smile is universal welcome.",
  "Tech improves, not controls.",
  "Stars shine in darkness.",
  "Failure is opportunity smarter.",
  "Create your own future.",
  "Life is short, make sweet.",
  "Love the life you live.",
  "Where there's love, there's life.",
  "Make each day a masterpiece.",
  "Life, a daring adventure.",
  "Live each second boldly.",
  "Life is simple, not complicated.",
  "In three words: life goes on.",
  "Life is short, make sweet.",
  "Life is what happens.",
  "Biggest adventure: live dreams.",
  "Good life inspired by love.",
  "Life is short, make sweet.",
  "Friends, books, sleepy conscience.",
  "New adventures awaken the spirit.",
  "Immerse in the beauty of diversity.",
  "Cultivate gratitude, harvest joy.",
  "Explore ideas, ignite innovation.",
  "Growth begins outside comfort zones.",
  "Sunflowers follow the sun's journey.",
  "Kindness ripples, creating waves.",
  "Learn from yesterday, thrive today.",
  "Harmony blooms in mindful hearts.",
  "Nourish the soul with nature's symphony.",
  "Radiate positivity, attract happiness.",
  "Discover the magic within challenges.",
  "Embrace the rhythm of life.",
  "Leap into the unknown with courage.",
  "Dream big, work hard, stay humble.",
  "Unlock potential through persistence.",
  "Find joy in the ordinary moments.",
  "Create your path, leave a trail.",
  "Cherish connections, nurture friendships.",
  "Navigate storms, find your rainbow.",
  "Listen to whispers of the wind.",
  "Wisdom grows through shared experiences.",
  "Embrace the dance of serendipity.",
  "Illuminate darkness with your light.",
  "Strive for progress, not perfection.",
  "Spark curiosity, unlock potential.",
  "Dwell in possibility, not limitation.",
  "Time spent in nature is never wasted.",
  "Celebrate the journey, not just destination.",
  "Radiate kindness like the sun.",
  "Embrace change, welcome growth.",
  "Live in the present, savoring each moment.",
  "Create your story, let it be extraordinary.",
  "Express gratitude, the key to abundance.",
  "Every flower blooms at its own pace.",
  "Open your heart; let the universe in.",
  "Sow seeds of kindness, reap joy.",
  "Dream without fear, live without limits.",
  "Let go of what no longer serves you.",
  "Breathe in possibilities, exhale doubt.",
  "Collect moments, not things.",
  "Be the reason someone smiles today.",
  "Wander where the WiFi is weak.",
  "Happiness is homemade, savor every recipe.",
  "Leap into the unknown, discover your wings.",
  "Explore the world with a curious heart.",
  "Blossom where you are planted.",
  "Find solace in the symphony of rain.",
  "Admire the stars, but be one too.",
  "Chase sunsets, not people.",
  "Create a life you don't need a vacation from.",
  "Seek magic in the ordinary.",
  "Life is an adventure; enjoy the ride.",
  "Cherish silence; it has much to say.",
  "Radiate positivity, attract abundance.",
  "Plant seeds of kindness, watch them grow.",
  "Life is a canvas; paint it vibrant.",
  "Dance through life with purpose.",
  "Let your light shine, inspire others.",
  "Embrace the ebb and flow of life.",
  "Write your story with ink of passion.",
  "Chase dreams, not perfection.",
  "Radiate love; it's a universal language.",
  "Forge your path with courage and resilience.",
  "See the world through the lens of gratitude.",
  "Let your heart beat to the rhythm of joy.",
  "Create a symphony with the music of kindness.",
  "Celebrate small victories, they lead to big ones.",
  "Cherish the journey as much as the destination.",
  "Embrace challenges; they mold your character.",
  "Dwell in the beauty of simplicity.",
  "Climb mountains not to conquer, but to understand.",
  "Find joy in the journey of self-discovery.",
  "Life is a garden; tend to it with love.",
  "Cultivate resilience, weather life's storms.",
  "Breathe in peace, exhale chaos.",
  "Embrace the symphony of life's highs and lows.",
  "Be the reason someone believes in goodness.",
  "Navigate life's river with a resilient spirit.",
  "Build bridges, not walls.",
  "Radiate positive vibes, attract kind souls.",
  "Celebrate the beauty of imperfection.",
  "Craft your destiny with choices, not chances.",
  "Blossom where you are, bloom where you're planted.",
  "Chase sunsets, not people.",
  "Create a symphony with the music of kindness.",
  "Code fuels digital evolution.",
  "Innovate, adapt, overcome.",
  "Tech empowers endless ideas.",
  "Debugging: finding magic bugs.",
  "Craft elegant code always.",
  "JavaScript: language of web.",
  "Logic guides coding journey.",
  "Dev life: code, test, repeat.",
  "Binary thoughts, digital world.",
  "Create, iterate, improve code.",
  "APIs unlock data's potential.",
  "Machine learns, human codes.",
  "Code speaks louder than words.",
  "Hack the future with code.",
  "Pixels dance on screens.",
  "Dream big, code bigger.",
  "Commit to coding excellence.",
  "Tech dreams, code reality.",
  "Git commit, stay positive.",
  "Infinite loops, endless code.",
  "Web development: endless possibilities.",
  "Pixel perfect code matters.",
  "Tech wizards craft software.",
  "Software eats the world.",
  "Bug-free code, pure bliss.",
  "Git push to deploy.",
  "Logical minds, creative code.",
  "Code with passion, thrive.",
  "Algorithms shape the future.",
  "Agile minds, agile code.",
  "Celebrate small victories; they lead to big ones.",
];
